# brew tap-new uses this file to generate an autobump workflow for the new tap
name: brew bump

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/autobump.yml
  schedule:
    # Every day at 4:50 UTC
    - cron: 50 4 * * *
  workflow_dispatch: {}

permissions: {}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  autobump:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Mint App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.RELEASE_PLEASE_APP_CLIENT_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@f8d4222eb633e65c2a0157383cf80861fc7fae7f # 2026.09.07.1

      - name: Set up git
        id: git_setup
        uses: Homebrew/actions/git-user-config@f8d4222eb633e65c2a0157383cf80861fc7fae7f # 2026.09.07.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          username: ${{ steps.app-token.outputs.app-slug }}[bot]

      - name: Bump formulae
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ steps.app-token.outputs.token }}
          HOMEBREW_GIT_COMMITTER_NAME: ${{ steps.git_setup.outputs.name }}
          HOMEBREW_GIT_COMMITTER_EMAIL: ${{ steps.git_setup.outputs.email }}
          TAP_NAME: ${{ steps.set-up-homebrew.outputs.tap-name }}
        run: brew bump --no-fork --open-pr --formulae --bump-synced --tap="$TAP_NAME"
